# Generated by Django 3.1.3 on 2020-11-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201128_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='fav',
            field=models.BooleanField(default=False),
        ),
    ]
