# Generated by Django 3.1.3 on 2020-11-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201128_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='link',
            field=models.CharField(default='DEFAULT VALUE', max_length=2000),
        ),
    ]
