# Generated by Django 3.1.3 on 2020-12-04 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201204_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.account'),
        ),
    ]
