# Generated by Django 3.1.3 on 2020-12-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='link',
            field=models.CharField(default='Add link here', max_length=2000),
        ),
    ]
